config/routes.rb
Rails.application.routes.draw do
  get 'purchase_items/create'

  get 'purchase_items/update'

  get 'purchase_items/destroy'

  get 'carts/show'

  devise_for :users, :controllers => { registrations: 'registrations' }
  mount RedactorRails::Engine => '/redactor_rails'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'welcome#index'

  resources :posts
  resources :profiles
  resources :purchases
  resource :cart, only: [:show]
  resources :purchase_items, only: [:create, :update, :destroy]
  resources :pages
  resources :contacts
  resources :users
  resources :subscribers
  
  get 'search', to: 'searches#search'
  get 'console', to: 'posts#console'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	has_many :sections, as: :sectionable, dependent: :destroy
  accepts_nested_attributes_for :sections, allow_destroy: true
  attachment :profile_image
  has_many :purchase_items
  has_many :purchases
  default_scope { where(published: true) }
  has_many :users, through: :purchases
  validates :title, presence: true
  validates :short_description, presence: true
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]
  before_action :show_authorize, except: [:index]
  before_filter :find_profile, :only => [:show, :edit, :update, :destroy]

  def index
    @profiles = Profile.all
    @purchases = Purchase.all
    @all_purchase_items = PurchaseItem.all
    @purchase_item = current_purchase.purchase_items.new
    if params[:q].present?
      @profilesearch = Profile.search params[:q], fields: [:title, :body], operator: "or", suggest: true
    end
  end

  def show
    if params[:q].present?
      @profilesearch = Profile.search params[:q], fields: [:title, :body], operator: "or", suggest: true
    else
      @profile = Profile.find(params[:id])
      @current_user = current_user
      if @profile.published
        respond_to do |format|
          format.html # show.slim
          format.xml  { render :xml => @profile }
        end
      else
        redirect_to profiles_path, notice: 'This is not the Profile you are looking for'
      end
    end
  end

  def create
    @profile = Profile.new(params[:profile])
    respond_to do |format|
      if @profile.save
        format.html  { redirect_to(@profile, :notice => 'Profile was successfully created.') }
        format.json  { render :json => @profile, :status => :created, :location => @profile }
      else
        format.html  { render :action => "new" }
        format.json  { render :json => @profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  def new
    @profile = Profile.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @profile }
    end
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        flash[:notice] = 'Profile was successfully updated.'
        format.html { redirect_to(@profile) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @profile.errors,
  	                :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to(profiles_url) }
      format.xml  { head :ok }
    end
  end

  private

  def find_profile
    @profile = Profile.find(params[:id])
  end

  def show_authorize
    profile_object = Profile.find(params[:id])
    purchase_item = PurchaseItem.where(profile_id:profile_object.id, user_id:current_user)
    if !purchase_item.present? || purchase_item.first.purchase.purchase_status_id != 2
      redirect_to profiles_path, {alert: "Please purchase this profile to view it."}
    end
  end
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/profiles/_profile_form.slim
= form_for purchase_item, remote: true do |f|
  h4.text-right
    | Price: 
    span[style="color: green"]
      = number_to_currency profile.price
  .input-group
    = f.hidden_field :quantity, value: 1, min: 1
  = f.hidden_field :profile_id, value: profile.id
  = f.hidden_field :user_id, value: current_user.id
  = f.hidden_field :unit_price, value: profile.price
  - if current_user.present?
    .input-group
      = f.submit "Add to Cart", class: "btn btn-success-outline"
  - else
    p 
      | Please
      = link_to " Sign up ", new_user_registration_path
      | or 
      = link_to('Login', new_user_session_path, :class => ["nav-link"])
      |  to purchase a profile

app/views/profiles/_profiles.slim
- @profile.each do |profile|
	- if profile.published == true
  	h3 = link_to profile.title, profile_path(profile.id)
  	h4 = number_to_currency profile.price
  	p
  	- profile.sections.order("position asc").each do |section|
  		h4 = markdown(section.title)
  		= markdown(section.body)
  		hr
  	.btn.btn-success-outline =link_to profile.title, profile_path(profile.id)

  - else
	  h3 = link_to profile.title, profile_path(profile.id)
	  .btn.btn-success-outline Add To Cart

app/views/profiles/index.slim
.container
	h1
	  | Charity Profiles
	- if params[:q].present?
	  - if !@profilesearch.empty?
	    = render "shared/search_results"
	  - else
	    h3.topDown
	      | Your search returned no results... Try Again!
	    = render "shared/search_form"
	- else
		- my_items = Array.new #create array to track for purchased items
		-	@profiles.each do |profile|
			- my_items << profile.id #add all profile ids from each item to array
		- @all_purchase_items.each do |item|
			- if current_user.present?
				- if item.user_id == current_user.id && item.purchase.purchase_status_id == 2
					- profile = Profile.find_by_id(item.profile_id)
					- my_items.delete_if{|i|i==profile.id} #remove profile ids that have been purchased from id array
					h2 = profile.title
					.col-sm-4.no-left-pad.fill-image = image_tag(attachment_url(profile, :profile_image))
					.col-sm-8 = markdown(profile.short_description)
					= link_to "View Profile", profile_path(profile.id), class: "btn btn-success-outline"
					hr
		- my_items.each do |profile_id| #iterate through profile id array to show unpurchased profiles
			- if Profile.find_by_id(profile_id).present?
				- profile = Profile.find_by_id(profile_id)
				h2 = profile.title
				.col-sm-4.no-left-pad.fill-image = image_tag(attachment_url(profile, :profile_image))
				.col-sm-8 = markdown(profile.short_description)
				- if !current_user.present?
					h4.text-right
					  span[style="color: green"]
					    = number_to_currency profile.price

					= link_to("Login ", "#login", "data-toggle" => "modal", :class => ['nav-link'])
					span
						|  or 
					span = link_to("Sign Up", "#sign_up", "data-toggle" => "modal", :class => ['nav-link'])
					span
						|  to view profile
				- else
					= render "profile_form", profile: profile, purchase_item: @purchase_item
				hr

app/views/profiles/show.slim
- if params[:q].present?
  - if !@profilesearch.empty?
    = render "shared/search_results"
  - else
    h3.topDownWithNav
      | Your search returned no results... Try Again!
    = render "shared/search_form"
- else
  h2 = @profile.title
  h4 = convert_aud(@profile.price)
  - @profile.sections.order("position asc").each do |section|
    - if section.image_orientation == "right"
      .col-sm-12.profile-img
        .col-sm-6.text-center.pull-xs-left
          h3.add-top-padding = markdown(section.title)
          = markdown(section.body)
        .col-sm-6.pull-xs-right.profile-img
          = image_tag(attachment_url(section, :image))
    -elsif section.image_orientation == "left"
      .col-sm-12.profile-img
        .col-sm-6.pull-xs-left.profile-img
          = image_tag(attachment_url(section, :image))
        .col-sm-6.text-center.pull-xs-right.add-top-padding
          h3.add-top-padding = markdown(section.title)
          = markdown(section.body)
    -else section.image_orientation == "left"
      .col-sm-12.text-center.pull-xs-right
        h3.add-top-padding = markdown(section.title)
        = markdown(section.body)
      .col-sm-12.pull-xs-left.profile-img
        = image_tag(attachment_url(section, :image))
  = @profile.created_at.strftime("%d-%m-%Y")