config/routes.rb
Rails.application.routes.draw do
  get 'purchase_items/create'

  get 'purchase_items/update'

  get 'purchase_items/destroy'

  get 'carts/show'

  devise_for :users, :controllers => { registrations: 'registrations' }
  mount RedactorRails::Engine => '/redactor_rails'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'welcome#index'

  resources :posts
  resources :profiles
  resources :purchases
  resource :cart, only: [:show]
  resources :purchase_items, only: [:create, :update, :destroy]
  resources :pages
  resources :contacts
  resources :users
  resources :subscribers
  
  get 'search', to: 'searches#search'
  get 'console', to: 'posts#console'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :interests
  has_many :subscribers, through: :interests

  validates :category_name, presence: true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :email, presence: true
  validates :message, presence: true
  validates :poo_bear, absence: {message: "To have gotten here you must be a Terminator you cybernetic freak!"}
  validates_format_of :email, :with => /.+@.+\..+/i
end

app/models/footer.rb
class Footer < ActiveRecord::Base
  #add attachement declaration to models for refile image uploading
  attachment :footer_image1
  attachment :footer_image2
  attachment :footer_image3
end

app/models/image.rb
class Image < ActiveRecord::Base
	has_many :sections, as: :sectionable
end

app/models/interest.rb
class Interest < ActiveRecord::Base
	belongs_to :subscriber
  belongs_to :category

  validates :subscriber_id, :uniqueness => {:scope=>:category_id}
end

app/models/page.rb
class Page < ActiveRecord::Base
	attachment :page_image
end

app/models/post.rb
require 'elasticsearch/model'
class Post < ActiveRecord::Base
  has_many :sections, as: :sectionable, dependent: :destroy
  accepts_nested_attributes_for :sections, allow_destroy: true
  searchkick suggest: [:title]
  #add attachement declaration to moidels for refile image uploading
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  #validates_presence_of :title, :body
  attachment :profile_image
  attachment :image
  def search_data
    as_json only: [:name, :body]
    {
      title: title,
      body: body
    }
  end
  def should_index? #should only index the following
    title
    body
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	has_many :sections, as: :sectionable, dependent: :destroy
  accepts_nested_attributes_for :sections, allow_destroy: true
  attachment :profile_image
  has_many :purchase_items
  has_many :purchases
  default_scope { where(published: true) }
  has_many :users, through: :purchases
  validates :title, presence: true
  validates :short_description, presence: true
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :user
  belongs_to :profile
  belongs_to :purchase_status
  has_many :purchase_items
  before_create :set_purchase_status
  before_save :update_subtotal

  def subtotal
    purchase_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
	
	private

  def set_purchase_status
    self.purchase_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end


end

app/models/purchase_item.rb
class PurchaseItem < ActiveRecord::Base
  belongs_to :profile
  belongs_to :purchase
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :profile_present
  validate :purchase_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      profile.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def profile_present
    if profile.nil?
      errors.add(:profile, "is not valid or is not published.")
    end
  end

  def purchase_present
    if purchase.nil?
      errors.add(:purchase, "is not a valid purchase.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :post
  attachment :image
  belongs_to :sectionable, polymorphic: true
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
	has_many :interests
  has_many :categories, through: :interests
  belongs_to :user
  accepts_nested_attributes_for :categories

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :email, presence: true
  validates_uniqueness_of :email
  validates :poo_bear, absence: {message: "To have gotten here you must be a Terminator you cybernetic freak!"}
  validates_format_of :email, :with => /.+@.+\..+/i
 
  after_create :subscribe_user_to_mailing_list
  after_create :send_welcome_email_to_user
 
  private
 
    def subscribe_user_to_mailing_list
      SubscribeUserToMailingListJob.set(wait: 1.minute).perform_later(self)
    end
    def send_welcome_email_to_user
      if Rails.env.production?
        UserMailer.welcome_email(self).deliver_later!(wait: 2.minutes)
      else
        UserMailer.welcome_email(self).deliver_now
      end
    end
end

app/models/text.rb
class Text < ActiveRecord::Base
	has_many :sections, as: :sectionable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :subscriber
  has_many :purchases
  has_many :profiles, through: :purchases
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :email, presence: true
  validates :poo_bear, absence: {message: "To have gotten here you must be a Terminator you cybernetic freak!"}
  validates_format_of :email, :with => /.+@.+\..+/i
 
  #after_create :subscribe_user_to_mailing_list
 
  private
 
  def subscribe_user_to_mailing_list
    SubscribeUserToMailingListJob.perform_later(self)
  end
end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
  attachment :hero_image
  attachment :bodycontent_image
  attachment :aboutus_image
  attachment :pricing_image
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/footer_helper.rb
module FooterHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/shared/_footer.html.erb
<div class="row">
  <div class="container">
    <div class="col-sm-4 footer-column">
      <img src="https://scontent-lax3-1.xx.fbcdn.net/hphotos-xaf1/v/t1.0-9/10660365_10152400315681608_7014035543486940290_n.jpg?oh=bc183df1a9ade9abf26c301d98b715d4&oe=5724D276" alt="..." class="img-circle footer-images">
      <p class="topDown">
        The Team
      </p>
    </div>
    <div class="col-sm-4 footer-column">
      <img src="http://img-aws.ehowcdn.com/200x200/cme/cme_public_images/www_ehow_com/i.ehow.com/images/a06/ju/f6/print-like-old-typewriter-800x800.jpg" alt="..." class="img-circle footer-images">
      <p class="topDown">
        Get In Touch
      </p>
    </div>
    <div class="col-sm-4 footer-column">
      <img src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTNnVm1CSuIPw0dRo7LJR99zVA5fA3wvkVa9oaxY_pG-nl3VOva" alt="..." class="img-circle footer-images">
      <p class="topDown">
        Our Focus
      </p>
    </div>
  </div>
</div>

app/views/shared/_footer.slim
.row.footer-section
  .container
    hr
    .col-sm-4.footer-column
      = image_tag attachment_url(@footer_components, :footer_image1, :fill, 250, 250), :class=>"img img-circle footer-images"
      p.topDown
        h4 = @footer_components.footer_title1
        p = markdown(@footer_components.footer_body1)
    .col-sm-4.footer-column
      = image_tag attachment_url(@footer_components, :footer_image2, :fill, 250, 250), :class=>"img img-circle footer-images"
      p.topDown
        h4 = @footer_components.footer_title2
        p = markdown(@footer_components.footer_body2)
    .col-sm-4.footer-column
      = image_tag attachment_url(@footer_components, :footer_image3, :fill, 250, 250), :class=>"img img-circle footer-images"
      p.topDown
        h4 = @footer_components.footer_title3
        p = markdown(@footer_components.footer_body3)

app/views/shared/_search_form.slim
= form_for search_path, method: :get, :html => { :class =>'form-inline' } do |f|
  = text_field_tag :q, params[:q], :placeholder => "Search", :class =>'form-control searchBox'
  = submit_tag "Go", name: nil, :class => 'btn btn-success-outline'

app/views/shared/_search_results.slim
h2.topDown
  | Search Results...
ul
  - @postsearch.each do |post|
    li
      = link_to post.title, post_path(post.id)
    = markdown(post.body)

app/views/shared/_signup.slim
.container.jumbotron.newsletter
	h3.col-sm-12 Signup for our newsletter 
	.col-sm-12
		= form_for :subscribers, url:{:controller=>'subscribers', method: 'put', :action=>'create', :remote => true} do |f|
		    .form-group.col-sm-6 = f.text_field :first_name, :placeholder => "First Name", :class =>'form-control'
		    .form-group.col-sm-6 = f.text_field :last_name, :placeholder => "Last Name", :class =>'form-control'
		    .form-group.col-sm-6 = f.text_field :email, :placeholder => "Email", :class =>'form-control dropdown'
		   	.form-group.col-sm-6.select-dropdown = f.collection_select :category_ids, Category.all, :id, :category_name, {}, :class =>'dropdown-menu btn-group', :prompt => "I'm interested in..."
		    .poo-bear =f.text_field :poo_bear, :placeholder => "If you are Poo Bear you love eating out of these and you should leave it alone so you don't get stung by bees. If you are the Terminator then fill this out for sure!"
		    .col-sm-6
		    	= submit_tag "Go", name: nil, :class => 'btn btn-success-outline'